project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  reader-mode: true
  title: "Fundamentos de Acústica"
  search:
    location: sidebar
    type: overlay
  # navbar:
  #  background: dark
  sidebar:      
    - title: "Fundamentos de Acústica"
      # background: dark
      style: "docked"
      tools:
        - icon: github
          url: https://github.com/alvaradolucho 
      contents:
        - text: "---"
        - section: "Inicio"
          contents:
            - index.qmd
        - section: "Unidad 1 - Elementos del Sonido"
          contents:
            - sections/unidad1/principios-fisicos.qmd
            - sections/unidad1/principios-acustica.qmd
            - sections/unidad1/elementos-del-sonido.qmd
            - sections/unidad1/oscilaciones-tiempo-espacio.qmd

lightbox: true

format:
  html:
    code-fold: true
    theme:
      light: cosmo
      dark: darkly
    fontsize: 1.5em
    linestretch: 1.5
        
      
site-url: https://github.com/alvaradolucho/fundamentos_de_acustica