project:
  type: book
  output-dir: docs
theme:
  light: flatly
  dark: darkly

book:
  title: "Fundamentos de Acústica"
  chapters:
    - index.qmd
  site-url: https://github.com/alvaradolucho/fundamentos_quarto