---
title: "Principios de la Física"
---

En la física exploramos el comportamiento de los objetos. Desde una fracción pequeña de un protón hasta el universo mismo, contemplando aproximadamente 45 órdenes de magnitud ($10^{45}$). Para expresar las mediciones cuantitativamente, necesitamos introducir las **unidades de medida**. Las unidades fundamentales de la física son: **longitud**, **tiempo** y **masa**.

| Longitud | Tiempo | Masa |
|----------|--------|------|
| Metros | Segundos | Kilógramos |
| m | s | kg |

--- 

## Leyes de la Dinámica

El movimiento de los cuerpos en el tiempo y en el espacio está representada en las Leyes de Newton, en donde introduce y relaciona los conceptos de fuerza, masa y aceleración, es decir, el movimiento dado a partir de acciones sobre los cuerpos.

+ Primera Ley: Un objeto estático o a velocidad constante permanecerá en ese estado a menos que una fuerza sea aplicada sobre ese cuerpo.
+ Segunda Ley: Si se aplica una fuerza $F$ sobre un cuerpo de masa $m$, éste se moverá con una aceleración $a$ en la misma dirección de la fuerza. $$\sum_{i}F_i = ma$$
+ Tercera Ley: Si un objeto $A$ aplica una fuerza sobre un cuerpo $B$, éste último aplica una fuerza de la misma magnitud sobre el cuerpo $A$. Esta ley se conoce como "ley de acción-reacción". Este fenómeno no es muy intuitivo, pero a modo ilutrativo podemos decir que es lo que permite la propulsión de cohetes.
$$F_\text{acción} = - F_\text{reacción}$$

## Movimiento Armónico Simple

Considere una masa $m$ conectada a una pared rígida mediante un componente elástico (es decir, que pueda ser comprimido y descomprimido). Si se aplica una fuerza $F$ sobre la masa, el componente elástico se opondrá a la fuerza de manera proporcional al desplazamiento $x$, con lo que llamaremos "fuerza de restitución", de tal modo que: 

$$F_\text{restitución} = -kx$$

El balance de fuerzas en el sistema masa-resorte es entonces:

$$\begin{align*}
F_\text{restitución} & = ma \\
-kx &= ma \\
ma + kx &= 0
\end{align*}
$$

Recordando que la aceleración de un objeto es la segunda derivada de la posición, es decir $a = \ddot{x}(t)$, resulta entonces que:

$$\boxed{m\ddot{x} + kx = 0}$$

Esta ecuación la conocemos como **Movimiento Armónico Simple** y su solución es de forma ondulatoria:

$$x(t) = A\sin(\omega t + \phi)$$
donde:

+ $A$ es la amplitud de la onda.
+ $\omega=\sqrt{\dfrac{k}{m}} = 2\pi f$, con $f$ la frecuencia de oscilación en Hz.
+ $\phi$ es la fase o ángulo de desfase.

```{=html}
<iframe width="780" height="500" src="https://editor.p5js.org/alvaradolucho/full/_4eq2H00S"></iframe>
```


```{python}
import matplotlib.pyplot as plt
import numpy as np

a = 1.0
# f = 1
# omega = 2 * np.pi * f
k = 5000
m = [160, 80, 40]
legend_ = ['$m = $' + str(m_) + ' kg.' for m_ in m]
omega = np.sqrt(k / np.array(m))
linestyles = ['-b', '--r', '--k']
phi = 0.0
t = np.linspace(0, 2, 100)

fig, ax = plt.subplots()
for idx, om in enumerate(omega):
    x = a * np.sin(om * t + phi)
    plt.plot(t, x, linestyles[idx])
plt.xlabel('Tiempo $t$ en segundos')
plt.ylabel('Desplazamiento $x(t)$ en metros')
plt.title('Desplazamiento de la masa en el sistema masa resorte, con $k = ' + str(k) + ' \\frac{N}{m}$')
plt.xlim([t[0], t[-1]])
plt.legend(legend_)
```

<!--
<details>
<summary>Principios de la Dinámica</summary>


## Principios de la Dinámica

La posición de un cuerpo en un espacio se puede representar como en un **vector** en el espacio (para mayor simplicidad lo representaremos en un plano 2D). Si definimos un punto $r$ cuyas coordenadas $(r_x, r_y)$ dependen del tiempo, entonces:

$$\vec{r} = (r_x(t), r_y(t))$$

Si el cuerpo cambia de posición, lo hace en un tiempo determinado, de modo que aquel cambio de posición respecto del tiempo es llamado **velocidad** y se define como:

$$\vec{v}(r) = \dfrac{\Delta r}{\Delta t} = \dfrac{r_2 - r_1}{t_2 - t_1}$$

Además es de mucho interés conocer cómo la velocidad varía con el tiempo. Por ejemplo un bus frenando posee velocidad pero ésta va decayendo con el tiempo, o bien, si el bus va acelerando, significa que tiene velocidad y además ésta va aumentando con el tiempo. Podemos expresar matemáticamente esto como:

$$\vec{a} = \dfrac{\Delta v}{\Delta t}$$

Dentro de las conclusiones de la física del movimiento, tenemos que:

* El signo de las componentes de los vectores muestran la dirección del vector.
* Si $\vec{a}=\vec{0}$ y $\vec{v}\neq\vec{0}$, entonces el cuerpo está movíéndose en velocidad constante. 
* Si $\vec{a}=\vec{0}$ y $\vec{v} = \vec{0}$, entonces el cuerpo está en reposo (sin movimiento).

</details>
-->